; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Test Song:

.export _music_data:=music_data

music_data:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80, $32, $f9, $c3, $38, $f9, $c3, $3a, $f9, $83, $bf, $48, $ad, $44, $ad, $3a, $ad, $3e, $ad, $3a, $dd, $4a, $dd, $48
	.byte $bd, $9f, $38, $dd, $3a, $f9, $c3, $3e, $dd, $32
@song0ref38:
	.byte $dd, $00, $f9, $f9, $f9, $f9, $95
@song0ref45:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $3a, $f9, $c3, $3e, $f9, $c3, $40, $f9, $83, $bf, $36, $f9, $c3, $32, $dd, $3a, $dd, $38, $bd, $9f, $44, $dd, $40
	.byte $ad, $44, $ad, $32, $dd, $36, $dd, $38
	.byte $ff, $20
	.word @song0ref38
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $52, $dd, $58, $dd, $60, $dd, $50, $dd, $4a, $dd, $58, $9d, $bf, $56, $dd, $5c, $dd, $52, $dd, $58, $dd, $60, $bd
	.byte $9f, $50, $dd, $4a, $dd, $58, $dd, $56, $dd, $5c
	.byte $ff, $20
	.word @song0ref38
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $fd
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $ff, $19
	.word @song0ref45
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch3loop
