; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Test Song:

.export _music_data_test_song:=music_data_test_song

music_data_test_song:
	.byte 5
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : Song 2
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256
; 02 : Song 3
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word 307,256
; 03 : Song 4
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word 307,256
; 04 : Song 5
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.word 307,256

.export music_data_test_song
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env1, @env2, @env2
	.byte $00
	.byte $30 ; 01 : Instrument 1
	.word @env0, @env2, @env2
	.byte $00

@env0:
	.byte $c4,$cb,$cf,$00,$02
@env1:
	.byte $cf,$7f,$00,$00
@env2:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01, $80, $32, $f9, $c3, $38, $f9, $c3, $3a, $f9, $83, $bf, $48, $ad, $44, $ad, $3a, $ad, $3e, $ad, $3a, $dd, $4a
	.byte $dd, $48, $bd, $9f, $38, $dd, $3a, $f9, $c3, $3e, $dd, $00, $dd
@song0ch0loop:
@song0ref39:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $80, $3a, $f9, $c3, $3e, $f9, $c3, $40, $f9, $83, $bf, $36, $f9, $c3, $32, $dd, $3a, $dd, $38, $bd, $9f, $44, $dd, $40
	.byte $f9, $c3, $36, $dd, $00, $dd
@song0ch1loop:
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch1loop
@song0ch2:
	.byte $80, $52, $dd, $58, $dd, $60, $dd, $50, $dd, $4a, $dd, $58, $9d, $bf, $56, $dd, $5c, $dd, $52, $dd, $58, $dd, $60, $bd
	.byte $9f, $50, $dd, $4a, $dd, $58, $dd, $56, $dd, $00, $dd
@song0ch2loop:
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch2loop
@song0ch4:
@song0ch3:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97
@song0ch3loop:
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $ff, $19
	.word @song0ref39
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch3loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
@song1ref4:
	.byte $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b
	.byte $ff, $0c
	.word @song1ref4
	.byte $ff, $0c
	.word @song1ref4
	.byte $ff, $0c
	.word @song1ref4
	.byte $fd
	.word @song1ch0loop
@song1ch4:
@song1ch3:
@song1ch1:
@song1ch1loop:
	.byte $ff, $0c
	.word @song1ref4
	.byte $ff, $0c
	.word @song1ref4
	.byte $ff, $0c
	.word @song1ref4
	.byte $ff, $0c
	.word @song1ref4
	.byte $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref48:
	.byte $52, $f9, $83, $58, $f9, $83, $60, $f9, $83, $50, $f9, $83, $4a, $f9, $83, $58, $f9, $83, $56, $f9, $83, $5c, $f9, $83
	.byte $ff, $0c
	.word @song1ref48
	.byte $52, $f9, $c3, $5c, $bd, $58, $f9, $83, $56, $f9, $83, $58, $f9, $83, $52, $f9, $83, $56, $f9, $83, $4e, $f9, $83, $54
	.byte $f9, $83, $50, $dd, $4e, $9d, $50, $f9, $83, $4a, $f9, $83, $50, $f9, $83, $4e, $bd, $4a, $bd, $4e, $dd, $46, $9d, $40
	.byte $dd, $46, $9d, $4a, $f9, $a3, $00, $4a, $8f, $00, $4a, $93, $00, $4a, $97, $00, $95, $f9, $85, $4c, $bd, $4e, $bd, $fd
	.word @song1ch2loop
@song2ch0:
	.byte $fb, $01
@song2ch0loop:
	.byte $80
@song2ref5:
	.byte $3a, $91, $48, $a5, $44, $91, $40, $91, $44, $a5, $3a, $e1, $40, $a5, $3e, $a5, $38, $e1, $3e, $e1, $40, $e1, $3a, $91
	.byte $ff, $10
	.word @song2ref5
	.byte $3a, $e1, $38, $e1, $3a, $e1, $40, $91, $3c, $91, $40, $91, $44, $91, $3c, $a5, $40
@song2ref49:
	.byte $e1, $00, $f5
@song2ref52:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $0f
	.word @song2ref52
	.byte $f9, $f9, $cb, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $80
@song2ref78:
	.byte $30, $91, $3e, $a5, $3a, $91, $36, $91, $3a, $a5, $30, $e1, $36, $a5, $34, $a5, $40, $e1, $44, $e1, $48, $e1, $40, $91
	.byte $ff, $10
	.word @song2ref78
	.byte $32, $e1, $30, $e1, $32, $e1, $38, $91, $36, $91, $38, $91, $3a, $91, $38, $a5, $3a
	.byte $ff, $12
	.word @song2ref49
	.byte $ff, $0f
	.word @song2ref52
	.byte $f9, $f9, $cb, $fd
	.word @song2ch1loop
@song2ch4:
@song2ch3:
@song2ch2:
@song2ch2loop:
	.byte $ff, $0f
	.word @song2ref52
	.byte $ff, $0f
	.word @song2ref52
	.byte $ff, $0f
	.word @song2ref52
	.byte $f9, $f9, $cb, $fd
	.word @song2ch2loop
@song3ch0:
	.byte $fb, $01
@song3ch0loop:
@song3ref4:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $18
	.word @song3ref4
	.byte $fd
	.word @song3ch0loop
@song3ch4:
@song3ch3:
@song3ch2:
@song3ch1:
@song3ch1loop:
	.byte $ff, $18
	.word @song3ref4
	.byte $ff, $18
	.word @song3ref4
	.byte $fd
	.word @song3ch1loop
@song4ch0:
	.byte $fb, $01
@song4ch0loop:
	.byte $82
@song4ref5:
	.byte $40, $cd, $40, $a5, $44, $a5, $40, $cd, $3a, $a5, $3a, $a5, $f9, $a5, $36, $cd, $32, $a5, $36, $a5, $3a, $f5
@song4ref27:
	.byte $3a, $a5, $3c, $a5, $3a, $a5, $36, $a5, $36, $a5, $cf, $3a, $a5, $32, $f5, $30, $cd
	.byte $ff, $0c
	.word @song4ref5
	.byte $cf, $40, $cd, $44, $a5, $40, $a5, $44, $a5, $48, $a5, $4a, $a5, $40, $a5, $3c, $a5
	.byte $ff, $08
	.word @song4ref27
	.byte $32, $a5, $40, $f9, $a3, $3c, $f9, $a3, $fd
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $82
@song4ref80:
	.byte $3a, $f9, $a3, $36, $f5, $32, $a5, $f9, $a5, $2a, $f9, $a3, $32, $f9, $a3, $30, $f9, $a3, $cf, $28, $a5, $22, $f5, $28
	.byte $cd
	.byte $ff, $09
	.word @song4ref80
	.byte $3c, $f9, $a3, $40, $a5, $3a, $a5, $36, $cd, $32, $cd, $2c, $cd, $30, $f9, $a3, $2c, $f9, $a3, $fd
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $82
@song4ref132:
	.byte $4a, $f9, $a3, $48, $f5, $44, $a5, $f9, $a5, $3c, $f9, $a3, $36, $f5, $32, $f9, $cb, $a7, $2c, $f9, $cb, $1e, $cd
	.byte $ff, $09
	.word @song4ref132
	.byte $4a, $f9, $a3, $52, $cd, $48, $cd, $44, $f9, $a3, $40, $f9, $a3, $3c, $f9, $a3, $fd
	.word @song4ch2loop
@song4ch4:
@song4ch3:
@song4ch3loop:
@song4ref179:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $09
	.word @song4ref179
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song4ch3loop
