;
; File generated by cc65 v 2.19 - Git a88d7ab
;
	.fopt		compiler,"cc65 v 2.19 - Git a88d7ab"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_all
	.import		_ppu_on_all
	.export		_PALETTE
	.export		_main

.segment	"RODATA"

_PALETTE:
	.byte	$03
	.byte	$25
	.byte	$30
	.byte	$27
	.byte	$00
	.byte	$1C
	.byte	$20
	.byte	$2C
	.byte	$00
	.byte	$00
	.byte	$10
	.byte	$20
	.byte	$00
	.byte	$06
	.byte	$16
	.byte	$26
	.byte	$00
	.byte	$16
	.byte	$35
	.byte	$24
	.byte	$00
	.byte	$00
	.byte	$37
	.byte	$25
	.byte	$00
	.byte	$0D
	.byte	$2D
	.byte	$1A
	.byte	$00
	.byte	$0D
	.byte	$27
	.byte	$2A

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(_PALETTE)
	ldx     #>(_PALETTE)
	jsr     _pal_all
	jsr     _ppu_on_all
	jmp     L0002
L0002:	jmp     L0002
	rts

.endproc

