; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_win

@sfx_ntsc_win:
	.byte $81,$67,$82,$01,$80,$33,$84,$93,$85,$01,$83,$ff,$87,$93,$88,$01
	.byte $86,$8f,$89,$f0,$01,$80,$39,$01,$80,$3d,$01,$80,$3f,$11,$84,$7c
	.byte $87,$7c,$14,$81,$1c,$80,$33,$84,$ef,$85,$00,$87,$ef,$88,$00,$01
	.byte $80,$39,$01,$80,$3d,$01,$80,$3f,$25,$81,$fd,$82,$00,$80,$33,$84
	.byte $d5,$87,$d5,$01,$80,$39,$01,$80,$3d,$01,$80,$3f,$24,$00

.export sounds
