; This file is for the FamiTone2 library and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_win
	.word @sfx_ntsc_hurt
	.word @sfx_ntsc_sword

@sfx_ntsc_win:
	.byte $81,$67,$82,$01,$80,$33,$84,$93,$85,$01,$83,$33,$87,$93,$88,$01
	.byte $86,$8f,$89,$f0,$01,$80,$39,$83,$39,$01,$80,$3d,$83,$3d,$01,$80
	.byte $3f,$83,$3f,$11,$84,$7c,$83,$33,$87,$7c,$01,$83,$39,$01,$83,$3d
	.byte $01,$83,$3f,$11,$81,$1c,$80,$33,$84,$ef,$85,$00,$83,$33,$87,$ef
	.byte $88,$00,$01,$80,$39,$83,$39,$01,$80,$3d,$83,$3d,$01,$80,$3f,$83
	.byte $3f,$25,$81,$fd,$82,$00,$80,$33,$84,$d5,$83,$33,$87,$d5,$01,$80
	.byte $39,$83,$39,$01,$80,$3d,$83,$3d,$01,$80,$3f,$83,$3f,$24,$00
@sfx_ntsc_hurt:
	.byte $89,$f0,$00
@sfx_ntsc_sword:
	.byte $89,$f0,$00

.export sounds
